"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-idvabmvdbao@me2i+ynor6qq64h&&^b(tah3k^-j5kolv6qlvg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Ensure this includes the root templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'bookshelf.CustomUser'


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Ensure DEBUG is set to False for production
DEBUG = False  # Set this to True during local development but False in production

# Security Headers
SECURE_BROWSER_XSS_FILTER = True  # Enable the X-XSS-Protection header
SECURE_CONTENT_TYPE_NOSNIFF = True  # Enable the X-Content-Type-Options header
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking attacks

# HTTPS Cookies
CSRF_COOKIE_SECURE = True  # Send CSRF cookies over HTTPS only
SESSION_COOKIE_SECURE = True  # Send session cookies over HTTPS only

# Recommended: Define an ALLOWED_HOSTS list for production
ALLOWED_HOSTS = ['your-production-domain.com']  # Replace with actual domain



MIDDLEWARE += [
    'csp.middleware.CSPMiddleware',
]

CSP_DEFAULT_SRC = ["'self'"]
CSP_SCRIPT_SRC = ["'self'", 'https://trusted-scripts.com']
CSP_STYLE_SRC = ["'self'", 'https://trusted-styles.com']


# In settings.py
SECURE_SSL_REDIRECT = True

# In settings.py
SECURE_HSTS_SECONDS = 31536000  # 1 year

# In settings.py
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# In settings.py
SECURE_HSTS_PRELOAD = True

# In settings.py
SESSION_COOKIE_SECURE = True

# In settings.py
CSRF_COOKIE_SECURE = True

# In settings.py
X_FRAME_OPTIONS = 'DENY'

# In settings.py
SECURE_CONTENT_TYPE_NOSNIFF = True

# In settings.py
SECURE_BROWSER_XSS_FILTER = True

# Enforce HTTPS in production, particularly when behind a proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# SECURE_SSL_REDIRECT ensures that all HTTP requests are redirected to HTTPS.
SECURE_SSL_REDIRECT = True

# SECURE_HSTS_SECONDS specifies how long browsers should only access the site via HTTPS (1 year).
SECURE_HSTS_SECONDS = 31536000


